//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Questao5.Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Questao5.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Apenas contas correntes ativas podem consultar o saldo.
        /// </summary>
        public static string ContaCorrenteInactiveAccountException {
            get {
                return ResourceManager.GetString("ContaCorrenteInactiveAccountException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Apenas contas correntes cadastradas podem consultar o saldo..
        /// </summary>
        public static string ContaCorrenteInvalidAccountException {
            get {
                return ResourceManager.GetString("ContaCorrenteInvalidAccountException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Apenas contas correntes ativas podem receber movimentação;.
        /// </summary>
        public static string MovimentoInactiveAccountException {
            get {
                return ResourceManager.GetString("MovimentoInactiveAccountException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Apenas contas correntes cadastradas podem receber movimentação..
        /// </summary>
        public static string MovimentoInvalidAccountException {
            get {
                return ResourceManager.GetString("MovimentoInvalidAccountException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Apenas os tipos \&quot;débito\&quot; ou \&quot;crédito\&quot; podem ser aceitos..
        /// </summary>
        public static string MovimentoInvalidMovementTypeException {
            get {
                return ResourceManager.GetString("MovimentoInvalidMovementTypeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A requisição deve ser informada para haver movimentação..
        /// </summary>
        public static string MovimentoInvalidRequestException {
            get {
                return ResourceManager.GetString("MovimentoInvalidRequestException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Apenas valores positivos podem ser recebidos..
        /// </summary>
        public static string MovimentoInvalidValueException {
            get {
                return ResourceManager.GetString("MovimentoInvalidValueException", resourceCulture);
            }
        }
    }
}
